
tester: tester.hs
	ghc tester.hs

all: tester
	./x.sh \
ap.org \
articles.org \
exx-resource.org \
n-clitics.org \
np.org \
numerals-np.org \
numerals-simple.org \
phrases.org \
prep.org \
rel.org \
v-clitics-past-simul.org \
v-clitics-pres-simul.org \
v-clitics-variants.org \
vp.org \
vpslash.org
